andela/ninjas-ah-backend

- .eslintrc.json
- package-lock.json
- package.json
Configure ESLint
ESLint is the required linter for the project. It'll help check for style violations and flag them.
[#165412902](https://www.pivotaltracker.com/story/show/165412902)
> #165412902 Configure ESLint

- README.md
- Have TravisCI badge on ninjas-ah-backend repository
- Connect github repository with TravisCI
- Add travis markdown to readme file 
- It should be tested using TravisCI and the Github repository
- None
- [#165412900](https://www.pivotaltracker.com/story/show/165412900)
- None
- None
> [ch-165412900] add travis readme badge

- package-lock.json
Fix dependency issues in package-lock.json
Have the following dependencies removed in package-lock.json
- morgan
- slug
[#165560719](https://www.pivotaltracker.com/story/show/165560719)
> #165560719 fix dependency issues in package-lock.json

- package-lock.json
- package.json
Setup unit testing
Install the following packages:
- ``mocha``
- ``chai``
- ``chai-http``
-  ``nyc``
-  ``mocha-lcov-reporter``
-  ``coveralls``
[#165412905](https://www.pivotaltracker.com/story/show/165412905)
> #165412905 setup unit testing

- package-lock.json
- package.json
- templates/css/style.css
- templates/css/style.css.map
- templates/html/index.html
- templates/sass/style.scss
- Have html templates directory with sass css
- Create template directory
- Create subfolders inside template directory
- integrate sass css
- install and configure npm-sass library
- It should be tested by running the index file.
- None
- [#165412908](https://www.pivotaltracker.com/story/show/165412908)
- None
> [ch-165412908] add html templates directories with sass

- .codeclimate.yml
- .env.sample
- .nycrc
- README.md
This PR integrates Codeclimate and Coveralls test coverage
configure .codeclimate.yml file and .travis.yml for test coverage
you can test this by visiting andela/ninjas-ah-backend and scroll down to see Codeclimate and coverals badges in README
- N/A
- [165713687](https://www.pivotaltracker.com/story/show/165713687)
- N/A
- N/A
> #165713687 Integrate Coveralls  and Codeclimate

- package-lock.json
- package.json
- src/app.js
- swagger.json
- Have swagger documentation for APIs
- CRUD API test on swagger
- Using Swagger
- None
- (#165412907)[https://www.pivotaltracker.com/story/show/165412907]
> [ft-165412907] add swagger documentation

- package.json
- src/helpers/validation/email.js
- src/helpers/validation/index.js
- src/helpers/validation/newUser.js
- src/helpers/validation/password.js
- src/middlewares/validateNewUser.js
- src/tests/controllers/users.test.js
- src/tests/middlewares/validateNewUser.test.js
validate user input on signup
Send descriptive error messages when a user enters invalid parameters in an attempt to signup.
Invalid user parameters include:
- existing user email
- invalid email
- password of length less than 8
- password not being alphanumeric
- after cloning the repository, cd into it and type `npm run test`
- To test this feature in postman, go in the signup route, import and pass the `validateNewUser.js` middleware to validate user inputs
- none
[165412912](https://www.pivotaltracker.com/story/show/165412912)
- none
- none
> #165412912 validate user input on signup

- src/controllers/ArticleController.js
- src/migrations/20190529140817-create-favorite-article.js
- src/models/favoritearticle.js
- src/models/user.js
- src/queries/articles/index.js
- src/queries/favoriteArticles/favoriteArticle.js
- src/queries/favoriteArticles/getAllFavoritedArticles.js
- src/queries/favoriteArticles/index.js
- src/queries/favoriteArticles/removeFavoritedArticle.js
- src/routes/api/articles.js
- src/tests/models/favoriteArticleModel.test.js
- src/tests/models/index.js
- src/tests/queries/favoriteArticles/favoriteArticle.test.js
- src/tests/queries/favoriteArticles/getAllFavoritedArticles.test.js
- src/tests/queries/favoriteArticles/index.js
- src/tests/queries/favoriteArticles/removeFavoritedArticle.test.js
- src/tests/queries/index.js
- src/tests/routes/articles.test.js
- templates/html/articles.html
- templates/html/bookmark_article.html
- templates/html/chat.html
- templates/html/favorite_article.html
- templates/html/signup.html
- templates/js/index.js
Add endpoints to allow a user to favorite an article
Have the following endpoints working and accessible to an authenticated user
- `PATCH /api/v1/articles/:slug/favorite`
- `DELETE /api/v1/articles/:slug/favorite`
- `GET /api/v1/articles/favorited`
- After cloning the repo, cd into it and type `npm test`
- Using Postman, firstly make sure you signup then login to get the access token, secondly make sure you pass the access token in the header with the following key name: `access-token`, secondly create an article, and finally make any request to the above endpoints
- Using the mockup,  after running the server by typing `npm run start` or `npm run dev`, firstly create an account by visiting `http://localhost:<PORT>/mockups/signup.html`, then login by visiting …
> #166326326 favorite an article

- templates/html/login.html
Save the token in the local storage of the browser when a user is successfully logged in
[165412908](https://www.pivotaltracker.com/story/show/165412908)
> #165412908 save token in the localstorage

- src/controllers/UserController.js
- src/queries/users/getAllUser.js
- src/queries/users/index.js
- src/routes/api/users.js
- src/tests/routes/allUser.test.js
- src/tests/routes/index.js
Display users profiles
Having the following endpoints:
Post /api/v1/auth/signup
Post /api/v1/auth/login
POST /api/v1/users
After cloning the repo, run npm run dev command, the following endpoints in postman:
Post /api/v1/auth/signup
Post /api/v1/auth/login
POST /api/v1/users
Implemented using node.js, and express
What are the relevant pivotal tracker stories?
165412929
> # 165412929 Display users profiles

- src/controllers/UserController.js
- src/helpers/queryHelper.js
- src/queries/users/getAllUser.js
- src/routes/api/users.js
- src/tests/routes/allUser.test.js
- templates/html/allAuthors.html
- templates/html/articleLike.html
- templates/html/commentLike.html
- templates/html/comments.html
- templates/html/editComment.html
- templates/html/reportArticle.html
Add mockups
Having the following endpoint : 
Comment on an article:
* POST /api/v1/articles/:articleSlug/comment
* GET /api/v1/articles/:articleSlug/comments/
* DELETE /api/v1/articles/:articleSlug/comments/:commentId
Like a comment:
* POST /api/v1/articles/:articleSlug/comments/:commentId/like
Like an article:
* POST /api/v1/articles/:articleSlug/:status
Report an article:
* POST /api/v1/article/:articleSlug/report
* GET /api/v1/article/:articleSlug/report/
* GET /api/v1/article/:articleSlug/report/:id
* DELETE /api/v1/article/:articleSlug/report/:id
Edit comment history:
* PATCH  /api/v1/articles/:articleSlug/comments/:commentId
* GET /api/v1/articles/:articleSlug/comments/
Display user's functionalities:
* GET /api/v1/users
After cloning the repo, run the command **npm run dev** , then …
> # 165412908 add mock_ups

- src/controllers/ArticleLikeController.js
- src/controllers/CommentLikeController.js
- src/queries/articles/likes/create.js
- src/queries/articles/likes/createLike.js
- src/queries/articles/likes/index.js
- src/routes/api/likes.js
- src/tests/routes/articleLike.test.js
- src/tests/routes/commentLikes.test.js
- templates/html/allAuthors.html
- templates/html/articleLike.html
- templates/html/commentLike.html
- templates/html/comments.html
- templates/html/editComment.html
Display all users who liked & refactor mockups
Having following mockups:
- {HOST}/mockups/articleLike.html
* Get /api/v1/articles/:articleSlug/Likes
- {HOST}/mockups/commentLike.html
* Get /api/v1/articles/:articleSlug/comments/:commentId/likes
-  {HOST}/mockups/allAuthors.html
* Get /api/v1/articles/:articleSlug/users/authors
After cloning the repo locally, run **npm run dev** and open the following htlm files:
- {HOST}/mockups/articleLike.html
*Post /api/v1/articles/:articleSlug/:status
* Get /api/v1/articles/:articleSlug/Likes
- {HOST}/mockups/commentLike.html
* Post /api/v1/articles/:articleSlug/comments/:commentId/like
* Get /api/v1/articles/:articleSlug/comments/:commentId/likes
-  {HOST}/mockups/allAuthors.html
* Get /api/v1/articles/:articleSlug/users/authors
The project backend …
> #166057101 Display all users who liked & refactor mockups

- package-lock.json
- src/controllers/AuthLocalController.js
- src/controllers/NotificationController.js
- src/helpers/factory/report.js
- src/helpers/mailer/sendMail.js
- src/helpers/mailer/templates/notification.js
- src/helpers/notifications/commentArticle.js
- src/helpers/notifications/publishArticle.js
- src/helpers/notifications/sendNotification.js
- src/index.js
- src/middlewares/checkUpdateNotification.js
- src/migrations/20190427180244-create-user.js
- src/migrations/20190608160408-add-notification-preference-column.js
- src/migrations/20190609181916-add-notification-url-column.js
- src/migrations/20190611085335-add-user-isActive-column.js
- src/migrations/20190611100644-modify-article-coverUrl-column.js
- src/models/notification.js
- src/queries/notifications/createNotification.js
- src/queries/notifications/getAllNotifications.js
- src/queries/notifications/getOneNotification.js
- src/queries/notifications/index.js
- src/queries/notifications/removeNotification.js
- src/queries/notifications/updateNotifications.js
- src/routes/api/notifications.js
- src/tests/queries/notifications/index.js
- src/tests/queries/notifications/removeNotification.test.js
- src/tests/queries/notifications/updateNotifications.test.js
- src/tests/routes/notifications.test.js
- templates/html/notifications.html
Allow users to be able to receive notifications
Have the following endpoints accessible to an authenticated user:
- `GET /api/v1/notifications` :get all notifications
- `GET /api/v1/notifications/seen` :get all seen notifications
- `GET /api/v1/notifications/unseen` :get all unseen notifications
- `GET /api/v1/notifications/:notificationId` :get one notification
- `DELETE /api/v1/notifications/:notificationId` :delete one notification
- `GET /api/v1/notifications/configuration` :get notification configuration
- `POST /api/v1/notifications/configuration` :create notification configuration
- `PUT /api/v1/notifications/configuration` :update notification configuration
- `PUT /api/v1/notifications/:notificationId` :update notification
- `PUT /api/v1/notifications/seen` :update all …
> #165412926 send and show notifications

- src/app.js
- swagger.json
- Have swagger documentation for APIs
- After cloning the repo, cd into it and run the server with this command: `npm start`, then open the browser and go to the following address: `http://localhost:<PORT>/api/v1/documentation`
- For protected routes, you have to log in and get a token
- (#165412907)[https://www.pivotaltracker.com/story/show/165412907]
> #165412907 Add API documentation

- src/app.js
- src/controllers/ArticleController.js
- src/helpers/factory/user.js
- src/helpers/validation/updateArticle.js
- src/middlewares/checkArticlePemissions.js
- src/middlewares/validation/articles.js
- src/migrations/20190427195129-create-article.js
- src/migrations/20190611154523-add-article-rating-column.js
- src/queries/articles/update.js
- src/routes/api/articles.js
- src/routes/api/comments.js
- src/routes/api/likes.js
- src/routes/api/rating.js
- src/routes/api/reports.js
- src/routes/api/tags.js
- src/routes/api/upload.js
- src/tests/controllers/ArticleController.test.js
- src/tests/middlewares/checkPermission.test.js
- src/tests/queries/articles/update.test.js
- src/tests/routes/articleLike.test.js
- src/tests/routes/userArticles.test.js
- swagger.json
Apply Permissions Middleware in routes
> Add permissions in routes

- src/controllers/RatingController.js
- src/queries/index.js
- src/queries/ratings/getAll.js
- src/queries/ratings/index.js
- src/queries/ratings/sortArticlesByRatings.js
- src/queries/users/index.js
- src/routes/api/index.js
- src/routes/api/rating.js
- src/tests/controllers/RatingController.test.js
- Add pagination support for article's ratings
- sort articles by rating
creating the following endpoints:
`` GET /api/v1/rating/articles/:slug?limit&offset ``
`` GET /api/v1/rating/articles?limit&offset ``
clone the repo locally and user postman to test endpoints
- test endpoints with Mocha and Chai
#165412920
> #165412920 article rating pagination

- src/controllers/AuthLocalController.js
- src/controllers/ReadingStatController.js
- src/middlewares/validation/articles.js
- src/migrations/20190612124112-change-readtime-column-type.js
- src/routes/api/readingStats.js
- src/tests/routes/index.js
- src/tests/routes/readingStats.test.js
- templates/html/readingStats.html
Fix readtime bug when updating the article
> Fix readtime bug

- .travis.yml
- package.json
- src/config/status.js
- src/controllers/AuthLocalController.js
- src/controllers/AuthPassportController.js
- src/helpers/checkCreateUpdateUserErrors.js
- src/helpers/index.js
- src/helpers/mailer/templates/resetPassword.js
- src/helpers/urlHelper.js
- src/middlewares/verifyAdmin.js
- src/routes/auth/index.js
- src/tests/controllers/AuthPassportController.test.js
- src/tests/routes/users.test.js
Enable social media login/signup
Allow a user to be able Signup/Register to Authors Haven using google, facebook and twitter
After cloning the repo, cd into it and type `npm test`
[165412915](https://www.pivotaltracker.com/story/show/165412915)
> #165412915 Redirect on social login/signup

- src/controllers/UserController.js
- src/helpers/mailer/templates/index.js
- src/helpers/mailer/templates/updateEmail.js
- src/middlewares/checkUpdateUser.js
- src/routes/api/users.js
- src/tests/routes/users.test.js
Add an endpoint that allows users to update their profile
- Have the following endpoint accessible to an authenticated user: `PUT /api/v1/users`
- Send a confirmation email when a user tries to update his/her email
- After cloning the repo, cd into it and type `npm test`
- Using Postman, firstly make sure you signup then login to get the access token, secondly make sure you pass the access token in the header with the following key name: `access-token` to be able to edit the profile
[165412916](https://www.pivotaltracker.com/story/show/165412916)
> #165412916 Send confirmation email when email is updated

- src/controllers/AuthLocalController.js
- src/helpers/mailer/templates/resetPassword.js
- src/migrations/20190715122848-modify-token-column-length.js
- templates/html/chat.html
Changes applied in the mail template.
> Fix reset password template

- src/controllers/ArticleController.js
- src/controllers/UploadController.js
- src/helpers/searchArticleFilters/filterQueryBuilder.js
- src/helpers/validation/createArticle.js
- src/helpers/validation/updateArticle.js
- src/middlewares/checkArticlePermissions.js
- src/migrations/20190717132403-change-rating-column-in-article.js
- src/queries/ratings/update.js
- src/routes/api/articles.js
- src/tests/controllers/ArticleController.test.js
- src/tests/controllers/RatingController.test.js
- src/tests/queries/articles/create.test.js
- src/tests/queries/articles/getAll.test.js
- src/tests/queries/articles/searchFilters.test.js
- src/tests/queries/ratings/create.test.js
- src/tests/queries/ratings/get.test.js
- src/tests/queries/tags/get.test.js
- Fix how search queries are built
- Add **cloudinary** image version when uploading an image
- Remove draft articles to be shown on public
- Change article validation
- Rename `checkArticlePermissions` middleware
`run npm test`
N/A
N/A
N/A
N/A
> Fix article bugs

- src/config/dbConfig.js
- src/controllers/HighlightController.js
- src/helpers/queryHelper.js
- src/helpers/validation/createHighlight.js
- src/middlewares/checkArticle.js
- src/migrations/20190721221857-modify-highlight-highlightedText-column.js
- src/migrations/20190723093356-add-highlight-anchor-key-column.js
- src/models/highlight.js
- src/queries/highlights/getAll.js
- src/routes/api/highlights.js
- src/seeders/20190605075225-permissions.js
- src/seeders/20190715123639-admin-user.js
- src/tests/routes/highlight.test.js
Allow users to be able to highlight and comment on any text of an article
- Allow a user to highlight a text of an article without being required to comment
After cloning the repo, cd into it and type `npm test`
[165412893](https://www.pivotaltracker.com/story/show/165412893)
> #165412893 highlight article

- src/controllers/ArticleController.js
change the response when deleting a bookmark
> Change response remove bookmarks

- package-lock.json
- src/controllers/ArticleController.js
#What this PR do
- save article's likes and dislike  as a number by default will be 0
> save article likes and dislikes as number

- src/controllers/AuthLocalController.js
- src/controllers/NotificationController.js
- src/controllers/PermissionController.js
- src/controllers/ReportController.js
- src/helpers/factory/permissionsAdmin.js
- src/helpers/validation/newUser.js
- src/helpers/validation/updateUser.js
- src/middlewares/checkReport.js
- src/middlewares/checkSignUpPermission.js
- src/middlewares/checkUpdateUser.js
- src/queries/permissions/index.js
- src/queries/reports/getAll.js
- src/routes/api/permissions.js
- src/routes/api/reports.js
- src/routes/api/users.js
- src/seeders/20190715123639-admin-user.js
- src/tests/controllers/UserController.test.js
- src/tests/routes/permission.test.js
- src/tests/routes/report.test.js
- src/tests/routes/users.test.js
Get all reports
Having the following endpoint accessible to an admin user: `/api/v1/article/reports`
After cloning the repo, cd into it and type `npm test`
[165412935](https://www.pivotaltracker.com/story/show/165412935)
> #165412935 report article

- src/controllers/ArticleController.js
- src/controllers/CommentController.js
- src/helpers/articles/counter.js
- src/helpers/articles/index.js
- src/helpers/index.js
- src/helpers/queryHelper.js
- src/models/comment.js
- src/queries/articles/getAll.js
- src/queries/articles/getArticlesCounter.js
- src/queries/articles/index.js
- src/queries/comments/getAll.js
- src/queries/comments/getSingle.js
- Articles count helper
- Get information about a created comment
- Add comment author in comments listing
> Articles and Comments bug fix 

- src/controllers/CommentLikeController.js
Change the response after liking comments, and get all likes
> Change the response after liking

- src/controllers/AuthLocalController.js
- src/controllers/AuthPassportController.js
- src/controllers/ReportController.js
- src/controllers/UserController.js
- src/queries/users/index.js
- src/queries/users/searchUsersByUsername.js
- src/routes/api/reports.js
- src/routes/api/users.js
- src/tests/controllers/AuthPassportController.test.js
- src/tests/routes/users.test.js
Allow an admin to delete any report or reported article and search users by username
Make the following endpoints accessible to an authorized admin:
- `GET /users/username/:username` (to filter results, you can append `offset` or `limit` on the URL)
- `DELETE /article/:articleSlug/report/:reportId`
- After cloning the repo, cd into it and type `npm install && npm run test`
[165412892](https://www.pivotaltracker.com/story/show/165412892)
> #165412892 delete report

- src/controllers/AuthPassportController.js
Activate an account  created using social media platforms
> active social media accounts

- src/controllers/UserController.js
- src/queries/follows/followUser.js
#What does this PR do?
- Fix the returned data when fetching followers
#Description of Task to be completed?
- When returning data should contain all followed user information.
#How should this be manually tested?
- clone the branch locally
#Any background context you want to provide?
N/A
#What are the relevant pivotal tracker stories?
- N/A
Screenshots (if appropriate)
> fix follow unfollow

- src/controllers/CommentController.js
- src/queries/articles/get.js
- src/routes/api/articles.js
- Return all comment edit history
- Add lastName and firstName of the author when fetching article
> Fix comment edit history bug
